// src/app/core/theme/theme-monochrome.ts

type MonochromeThemeMode = 'light' | 'dark';

const MONOCHROME_LIGHT_VARIABLES: Readonly<Record<string, string>> = {
  '--color-page-background': '#f4f4f4',
  '--color-surface-primary': '#ffffff',
  '--color-surface-secondary': '#ececec',
  '--color-surface-elevated': '#fafafa',
  '--color-surface-hover': '#e3e3e3',
  '--color-surface-active': '#d7d7d7',
  '--color-surface-disabled': '#efefef',
  '--color-text-primary': '#1c1c1c',
  '--color-text-secondary': '#5f5f5f',
  '--color-text-muted': '#737373',
  '--color-text-disabled': '#8a8a8a',
  '--color-text-inverse': '#ffffff',
  '--color-border-subtle': '#d1d1d1',
  '--color-border-strong': '#acacac',
  '--color-action-primary': '#3a3a3a',
  '--color-action-primary-hover': '#272727',
  '--color-action-primary-active': '#161616',
  '--color-action-primary-text': '#ffffff',
  '--color-action-secondary': '#e6e6e6',
  '--color-action-secondary-hover': '#d8d8d8',
  '--color-action-secondary-active': '#c9c9c9',
  '--color-action-secondary-text': '#2b2b2b',
  '--color-action-disabled': '#dddddd',
  '--color-action-disabled-text': '#777777',
  '--color-accent': '#656565',
  '--color-accent-text': '#ffffff',
  '--color-accent-subtle': '#dedede',
  '--color-brand-soft': '#b8b8b8',
  '--color-brand-subtle': '#e7e7e7',
  '--color-focus': '#404040',
  '--color-success': '#4b4b4b',
  '--color-warning': '#686868',
  '--color-danger': '#2b2b2b',
  '--color-error': '#2b2b2b',
  '--color-info': '#5a5a5a',
  '--color-icon-primary': '#2a2a2a',
  '--color-icon-secondary': '#5f5f5f',
  '--color-icon-muted': '#808080',
  '--color-selection-background': '#c5c5c5',
  '--color-selection-text': '#1c1c1c',
  '--color-backdrop': 'rgb(20 20 20 / 0.56)',
  '--color-field-background': '#ffffff',
  '--color-field-background-disabled': '#efefef',
  '--color-field-text': '#1c1c1c',
  '--color-field-placeholder': '#7b7b7b',
  '--color-field-hint': '#656565',
  '--color-field-border': '#acacac',
  '--color-field-border-hover': '#858585',
  '--color-field-border-focus': '#404040',
  '--color-field-border-invalid': '#4f4f4f',
  '--color-field-border-confirmed': '#666666',
  '--color-field-border-disabled': '#d1d1d1',
  '--color-field-error': '#3d3d3d',
  '--color-field-confirmed': '#575757',
  '--color-field-focus-ring': 'rgb(64 64 64 / 0.2)',
};

const MONOCHROME_DARK_VARIABLES: Readonly<Record<string, string>> = {
  '--color-page-background': '#111111',
  '--color-surface-primary': '#1b1b1b',
  '--color-surface-secondary': '#272727',
  '--color-surface-elevated': '#303030',
  '--color-surface-hover': '#333333',
  '--color-surface-active': '#404040',
  '--color-surface-disabled': '#242424',
  '--color-text-primary': '#f4f4f4',
  '--color-text-secondary': '#c6c6c6',
  '--color-text-muted': '#9b9b9b',
  '--color-text-disabled': '#767676',
  '--color-text-inverse': '#111111',
  '--color-border-subtle': '#444444',
  '--color-border-strong': '#646464',
  '--color-action-primary': '#d4d4d4',
  '--color-action-primary-hover': '#e0e0e0',
  '--color-action-primary-active': '#ededed',
  '--color-action-primary-text': '#161616',
  '--color-action-secondary': '#303030',
  '--color-action-secondary-hover': '#3a3a3a',
  '--color-action-secondary-active': '#464646',
  '--color-action-secondary-text': '#f4f4f4',
  '--color-action-disabled': '#373737',
  '--color-action-disabled-text': '#8f8f8f',
  '--color-accent': '#b7b7b7',
  '--color-accent-text': '#151515',
  '--color-accent-subtle': '#3c3c3c',
  '--color-brand-soft': '#6a6a6a',
  '--color-brand-subtle': '#2e2e2e',
  '--color-focus': '#e2e2e2',
  '--color-success': '#b8b8b8',
  '--color-warning': '#d0d0d0',
  '--color-danger': '#a3a3a3',
  '--color-error': '#a3a3a3',
  '--color-info': '#c3c3c3',
  '--color-icon-primary': '#f4f4f4',
  '--color-icon-secondary': '#c6c6c6',
  '--color-icon-muted': '#929292',
  '--color-selection-background': '#5b5b5b',
  '--color-selection-text': '#f4f4f4',
  '--color-backdrop': 'rgb(0 0 0 / 0.74)',
  '--color-field-background': '#1b1b1b',
  '--color-field-background-disabled': '#242424',
  '--color-field-text': '#f4f4f4',
  '--color-field-placeholder': '#929292',
  '--color-field-hint': '#c0c0c0',
  '--color-field-border': '#646464',
  '--color-field-border-hover': '#848484',
  '--color-field-border-focus': '#e2e2e2',
  '--color-field-border-invalid': '#b8b8b8',
  '--color-field-border-confirmed': '#cccccc',
  '--color-field-border-disabled': '#444444',
  '--color-field-error': '#d0d0d0',
  '--color-field-confirmed': '#d8d8d8',
  '--color-field-focus-ring': 'rgb(226 226 226 / 0.2)',
};

/** Liefert eine eigenständige Schwarzweiß-Palette für den aktuellen Darstellungsmodus. */
export function getMonochromeVariables(
  mode: MonochromeThemeMode,
): Readonly<Record<string, string>> {
  return mode === 'dark' ? MONOCHROME_DARK_VARIABLES : MONOCHROME_LIGHT_VARIABLES;
}
