// src/app/core/theme/theme-palettes.ts

import type { ThemeMode, ThemeName } from './theme.service';

interface ThemePaletteInput {
  page: string;
  surface: string;
  elevated: string;
  text: string;
  muted: string;
  border: string;
  primary: string;
  primaryHover: string;
  primaryText: string;
  accent: string;
  accentText: string;
  success: string;
  warning: string;
  danger: string;
  info: string;
}

type AlternativeThemeName = Exclude<ThemeName, 'default'>;
type ThemePaletteMap = Record<AlternativeThemeName, Record<ThemeMode, ThemePaletteInput>>;

const PALETTES: ThemePaletteMap = {
  neon: {
    light: {
      page: '#f7f6ff',
      surface: '#ffffff',
      elevated: '#fcfbff',
      text: '#1b1630',
      muted: '#6f6786',
      border: '#c7b9e9',
      primary: '#a620e8',
      primaryHover: '#8415c0',
      primaryText: '#ffffff',
      accent: '#00c9b7',
      accentText: '#0a2422',
      success: '#00a878',
      warning: '#e79a18',
      danger: '#f03a7f',
      info: '#256dff',
    },
    dark: {
      page: '#0b0814',
      surface: '#151020',
      elevated: '#21182f',
      text: '#fbf8ff',
      muted: '#a99dba',
      border: '#5d4777',
      primary: '#d45cff',
      primaryHover: '#e58cff',
      primaryText: '#15061d',
      accent: '#31f3da',
      accentText: '#061d1a',
      success: '#4de5a8',
      warning: '#ffc65a',
      danger: '#ff6c9f',
      info: '#6ca6ff',
    },
  },
  retro: {
    light: {
      page: '#f4ead6',
      surface: '#fff8e8',
      elevated: '#fffdf5',
      text: '#3b2d2a',
      muted: '#7d675d',
      border: '#bca17d',
      primary: '#b74f37',
      primaryHover: '#963d2b',
      primaryText: '#fff8e8',
      accent: '#2b7a78',
      accentText: '#f5fffd',
      success: '#4f7d4a',
      warning: '#c58527',
      danger: '#a73f4d',
      info: '#3d6b8a',
    },
    dark: {
      page: '#201b18',
      surface: '#2b2420',
      elevated: '#3a302a',
      text: '#f7ead2',
      muted: '#b9a88f',
      border: '#715c49',
      primary: '#e37a52',
      primaryHover: '#f0926f',
      primaryText: '#24120c',
      accent: '#66b5ad',
      accentText: '#102826',
      success: '#8eb77c',
      warning: '#dfae56',
      danger: '#d9747d',
      info: '#75a1bf',
    },
  },
  summer: {
    light: {
      page: '#fff7e7',
      surface: '#fffdf7',
      elevated: '#ffffff',
      text: '#42291f',
      muted: '#866a5d',
      border: '#e2b98b',
      primary: '#ef6b4a',
      primaryHover: '#d95134',
      primaryText: '#ffffff',
      accent: '#167f83',
      accentText: '#ffffff',
      success: '#5d9465',
      warning: '#d99329',
      danger: '#c65050',
      info: '#4c819d',
    },
    dark: {
      page: '#241713',
      surface: '#31201a',
      elevated: '#412a21',
      text: '#fff4dd',
      muted: '#c5a897',
      border: '#815b45',
      primary: '#ff8769',
      primaryHover: '#ffa08a',
      primaryText: '#2b1109',
      accent: '#54c4c0',
      accentText: '#092a2a',
      success: '#8bc48e',
      warning: '#efb65d',
      danger: '#ec7b76',
      info: '#83b5ca',
    },
  },
  nightsky: {
    light: {
      page: '#e7edf8',
      surface: '#f7f9fd',
      elevated: '#ffffff',
      text: '#18243d',
      muted: '#60708d',
      border: '#9daac1',
      primary: '#1f5f8f',
      primaryHover: '#174b73',
      primaryText: '#ffffff',
      accent: '#43c8e8',
      accentText: '#0c2930',
      success: '#4e8d80',
      warning: '#a8793d',
      danger: '#9d596c',
      info: '#397ba9',
    },
    dark: {
      page: '#070c18',
      surface: '#0e1728',
      elevated: '#17243a',
      text: '#f0f6ff',
      muted: '#95a5bf',
      border: '#344763',
      primary: '#56c8ef',
      primaryHover: '#82d8f5',
      primaryText: '#07131a',
      accent: '#56c8ef',
      accentText: '#07131a',
      success: '#73aa9d',
      warning: '#c49c62',
      danger: '#c77b8d',
      info: '#70b8df',
    },
  },
  ocean: {
    light: {
      page: '#edf7f8',
      surface: '#ffffff',
      elevated: '#f7fcfc',
      text: '#123239',
      muted: '#5a747a',
      border: '#9bbdc1',
      primary: '#147d8f',
      primaryHover: '#0d6473',
      primaryText: '#ffffff',
      accent: '#3ea6d8',
      accentText: '#082430',
      success: '#3f9175',
      warning: '#c18a37',
      danger: '#b45662',
      info: '#377fa6',
    },
    dark: {
      page: '#08181c',
      surface: '#10252a',
      elevated: '#17343a',
      text: '#ebfbfc',
      muted: '#91b0b5',
      border: '#35636a',
      primary: '#4bc3cf',
      primaryHover: '#75d3dc',
      primaryText: '#082226',
      accent: '#6bbce8',
      accentText: '#09202b',
      success: '#69bd99',
      warning: '#d6ad62',
      danger: '#d87883',
      info: '#76bce0',
    },
  },
  lava: {
    light: {
      page: '#f8eee9',
      surface: '#fffaf7',
      elevated: '#ffffff',
      text: '#3c211c',
      muted: '#805f56',
      border: '#c99d8b',
      primary: '#d94b2b',
      primaryHover: '#b83920',
      primaryText: '#ffffff',
      accent: '#f09a27',
      accentText: '#3a2004',
      success: '#638f5e',
      warning: '#d58a25',
      danger: '#c13e38',
      info: '#6b718f',
    },
    dark: {
      page: '#160b08',
      surface: '#24110d',
      elevated: '#371a12',
      text: '#fff3ea',
      muted: '#bf9b8e',
      border: '#724333',
      primary: '#ff6843',
      primaryHover: '#ff886a',
      primaryText: '#2c0b04',
      accent: '#ffb23f',
      accentText: '#2f1800',
      success: '#87b77d',
      warning: '#f2b759',
      danger: '#f17668',
      info: '#929bc4',
    },
  },
};

/** Erstellt die vollständigen semantischen Variablen eines alternativen Themes. */
function createVariables(palette: ThemePaletteInput): Record<string, string> {
  const mix = (color: string, amount: number, base: string): string =>
    `color-mix(in srgb, ${color} ${amount}%, ${base})`;

  return {
    '--color-page-background': palette.page,
    '--color-surface-primary': palette.surface,
    '--color-surface-secondary': mix(palette.primary, 8, palette.surface),
    '--color-surface-elevated': palette.elevated,
    '--color-surface-hover': mix(palette.primary, 12, palette.surface),
    '--color-surface-active': mix(palette.primary, 20, palette.surface),
    '--color-surface-disabled': mix(palette.muted, 8, palette.surface),
    '--color-text-primary': palette.text,
    '--color-text-secondary': mix(palette.text, 74, palette.page),
    '--color-text-muted': palette.muted,
    '--color-text-disabled': mix(palette.muted, 72, palette.page),
    '--color-text-inverse': palette.primaryText,
    '--color-border-subtle': mix(palette.border, 60, 'transparent'),
    '--color-border-strong': palette.border,
    '--color-action-primary': palette.primary,
    '--color-action-primary-hover': palette.primaryHover,
    '--color-action-primary-active': mix(palette.primary, 78, 'black'),
    '--color-action-primary-text': palette.primaryText,
    '--color-action-secondary': mix(palette.primary, 13, palette.surface),
    '--color-action-secondary-hover': mix(palette.primary, 20, palette.surface),
    '--color-action-secondary-active': mix(palette.primary, 28, palette.surface),
    '--color-action-secondary-text': palette.text,
    '--color-action-disabled': mix(palette.muted, 20, palette.surface),
    '--color-action-disabled-text': palette.muted,
    '--color-accent': palette.accent,
    '--color-accent-text': palette.accentText,
    '--color-accent-subtle': mix(palette.accent, 32, palette.surface),
    '--color-brand-soft': mix(palette.primary, 38, palette.surface),
    '--color-brand-subtle': mix(palette.primary, 12, palette.surface),
    '--color-focus': palette.primary,
    '--color-success': palette.success,
    '--color-warning': palette.warning,
    '--color-danger': palette.danger,
    '--color-error': palette.danger,
    '--color-info': palette.info,
    '--color-icon-primary': palette.text,
    '--color-icon-secondary': mix(palette.text, 74, palette.page),
    '--color-icon-muted': palette.muted,
    '--color-selection-background': mix(palette.primary, 46, palette.surface),
    '--color-selection-text': palette.text,
    '--color-backdrop': 'rgb(8 8 12 / 0.68)',
    '--color-field-background': palette.surface,
    '--color-field-background-disabled': mix(palette.muted, 10, palette.surface),
    '--color-field-text': palette.text,
    '--color-field-placeholder': palette.muted,
    '--color-field-hint': mix(palette.text, 70, palette.page),
    '--color-field-border': palette.border,
    '--color-field-border-hover': mix(palette.primary, 52, palette.border),
    '--color-field-border-focus': palette.primary,
    '--color-field-border-invalid': palette.danger,
    '--color-field-border-confirmed': palette.info,
    '--color-field-border-disabled': mix(palette.border, 55, 'transparent'),
    '--color-field-error': palette.danger,
    '--color-field-confirmed': palette.info,
    '--color-field-focus-ring': mix(palette.primary, 22, 'transparent'),
  };
}

/** Liefert die semantischen Variablen eines alternativen Themes. */
export function getThemeVariables(
  theme: AlternativeThemeName,
  mode: ThemeMode,
): Record<string, string> {
  return createVariables(PALETTES[theme][mode]);
}
